version: 2
updates:
  # Frontend dependencies (npm)
  - package-ecosystem: "npm"
    directory: "/ai-summarizer-frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-github-username"  # Replace with your actual username
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "npm"
      include: "scope"

  # Backend dependencies (.NET)
  - package-ecosystem: "nuget"
    directory: "/AISummarizerAPI"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-github-username"  # Replace with your actual username
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "nuget"
      include: "scope"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
