# ===================================================================
# Base Docker Compose Configuration
# This file contains shared configuration between dev and prod
# ===================================================================

version: '3.8'

x-backend-base: &backend-base
  build:
    context: ./AISummarizerAPI
    dockerfile: Dockerfile
  networks:
    - ai-summarizer-network
  healthcheck:
    test: ["CMD-SHELL", "curl -f http://localhost:80/api/summarization/health || exit 1"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s
  restart: unless-stopped

x-frontend-base: &frontend-base
  build:
    context: ./ai-summarizer-frontend
    dockerfile: Dockerfile
  networks:
    - ai-summarizer-network
  depends_on:
    backend:
      condition: service_healthy
  healthcheck:
    test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80/health || exit 1"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 10s
  restart: unless-stopped

services:
  backend:
    <<: *backend-base
    container_name: ai-summarizer-backend

  frontend:
    <<: *frontend-base
    container_name: ai-summarizer-frontend

networks:
  ai-summarizer-network:
    driver: bridge