# ===================================================================
# Development Override Configuration
# This file is automatically loaded by docker-compose in development
# ===================================================================

version: '3.8'

services:
  backend:
    build:
      target: runtime
    ports:
      - "5088:80"  # Expose for direct debugging
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_DETAILEDERRORS=true
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft=Information
      - Logging__LogLevel__Microsoft.Hosting.Lifetime=Information
    env_file:
      - ./.env.development
    volumes:
      - ./AISummarizerAPI/logs:/app/logs
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  frontend:
    build:
      target: development
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    volumes:
      - ./ai-summarizer-frontend/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro