services:
  backend:
    build:
      target: runtime
    ports:
      - "5088:80"  # Map external 5088 to internal 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_DETAILEDERRORS=true
      - ASPNETCORE_URLS=http://+:80
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft=Information
      - Logging__LogLevel__Microsoft.Hosting.Lifetime=Information
    env_file:
      - ./.env.development
    volumes:
      - ./AISummarizerAPI/logs:/app/logs
      # FIXED: Remove usersecrets volume for Docker
    networks:
      - ai-summarizer-network

  frontend:
    build:
      target: development
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ai-summarizer-network