name: 'Setup .NET Environment'
description: 'Sets up .NET SDK with caching and common configurations'
inputs:
  dotnet-version:
    description: '.NET version to install'
    required: false
    default: '9.0.x'
  working-directory:
    description: 'Working directory for .NET operations'
    required: false
    default: './AISummarizerAPI'
outputs:
  cache-hit:
    description: 'Whether NuGet cache was hit'
    value: ${{ steps.cache-nuget.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - name: Setup .NET ${{ inputs.dotnet-version }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Cache NuGet packages
      id: cache-nuget
      uses: actions/cache@v4
      with:
        path: |
          ~/.nuget/packages
          ${{ inputs.working-directory }}/obj
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Install .NET tools
      shell: bash
      run: |
        dotnet tool install --global dotnet-format --version 5.* || true
        dotnet tool install --global dotnet-reportgenerator-globaltool || true
        echo "$(dotnet --version) installed successfully"
